/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './Views/**/*.cshtml',
    './wwwroot/js/**/*.js',
    './node_modules/preline/dist/*.js',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 System Tokens
        'sys-primary': 'var(--md-sys-color-primary)',
        'sys-on-primary': 'var(--md-sys-color-on-primary)',
        'sys-primary-container': 'var(--md-sys-color-primary-container)',
        'sys-on-primary-container': 'var(--md-sys-color-on-primary-container)',
        'sys-secondary': 'var(--md-sys-color-secondary)',
        'sys-on-secondary': 'var(--md-sys-color-on-secondary)',
        'sys-secondary-container': 'var(--md-sys-color-secondary-container)',
        'sys-on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        'sys-tertiary': 'var(--md-sys-color-tertiary)',
        'sys-on-tertiary': 'var(--md-sys-color-on-tertiary)',
        'sys-tertiary-container': 'var(--md-sys-color-tertiary-container)',
        'sys-on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
        'sys-error': 'var(--md-sys-color-error)',
        'sys-on-error': 'var(--md-sys-color-on-error)',
        'sys-error-container': 'var(--md-sys-color-error-container)',
        'sys-on-error-container': 'var(--md-sys-color-on-error-container)',
        'sys-success': 'var(--md-sys-color-success)',
        'sys-on-success': 'var(--md-sys-color-on-success)',
        'sys-success-container': 'var(--md-sys-color-success-container)',
        'sys-on-success-container': 'var(--md-sys-color-on-success-container)',
        'sys-warning': 'var(--md-sys-color-warning)',
        'sys-on-warning': 'var(--md-sys-color-on-warning)',
        'sys-warning-container': 'var(--md-sys-color-warning-container)',
        'sys-on-warning-container': 'var(--md-sys-color-on-warning-container)',
        'sys-info': 'var(--md-sys-color-info)',
        'sys-on-info': 'var(--md-sys-color-on-info)',
        'sys-info-container': 'var(--md-sys-color-info-container)',
        'sys-on-info-container': 'var(--md-sys-color-on-info-container)',

        // MD3 Elevation & Surface Containers
        'sys-surface-dim': 'var(--md-sys-color-surface-dim)',
        'sys-surface': 'var(--md-sys-color-surface)',
        'sys-surface-bright': 'var(--md-sys-color-surface-bright)',
        'sys-surface-lowest': 'var(--md-sys-color-surface-container-lowest)',
        'sys-surface-low': 'var(--md-sys-color-surface-container-low)',
        'sys-surface-container': 'var(--md-sys-color-surface-container)',
        'sys-surface-high': 'var(--md-sys-color-surface-container-high)',
        'sys-surface-highest': 'var(--md-sys-color-surface-container-highest)',

        'sys-on-surface': 'var(--md-sys-color-on-surface)',
        'sys-on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'sys-outline': 'var(--md-sys-color-outline)',
        'sys-outline-variant': 'var(--md-sys-color-outline-variant)',

        // Backward compatibility mapping
        surface: 'var(--md-sys-color-surface-bright)',
        'surface-2': 'var(--md-sys-color-surface-container-low)',
        'surface-3': 'var(--md-sys-color-surface-container)',
        border: 'var(--md-sys-color-outline-variant)',
        ink: {
          DEFAULT: 'var(--md-sys-color-on-surface)',
          muted: 'var(--md-sys-color-on-surface-variant)',
          soft: 'var(--md-sys-color-outline)',
        },
        signal: 'var(--md-sys-color-primary)',
        live: 'var(--md-sys-color-error)',
        go: 'var(--md-sys-color-secondary)',
        warn: 'var(--md-sys-color-warning)',
        accent: 'var(--md-sys-color-tertiary)',
        'brand-success': 'var(--md-sys-color-success)',
        'brand-info': 'var(--md-sys-color-info)',
        'brand-warning': 'var(--md-sys-color-warning)',
        'brand-error': 'var(--md-sys-color-error)',
        'brand-primary': 'var(--md-sys-color-primary)',
      },
      fontFamily: {
        sans: ['Cairo', 'Almarai', 'Segoe UI', 'sans-serif'],
      },
      borderRadius: {
        xl: '14px',
        '2xl': '18px',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        float: 'var(--shadow-float)',
        topbar: 'var(--shadow-topbar)',
      },
      keyframes: {
        'eq-bar': {
          '0%, 100%': { transform: 'scaleY(0.35)' },
          '50%': { transform: 'scaleY(1)' },
        },
        'onair-pulse': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.45', transform: 'scale(0.82)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'eq-bar': 'eq-bar 1s ease-in-out infinite',
        'onair-pulse': 'onair-pulse 1.6s ease-in-out infinite',
        'fade-in': 'fade-in 0.25s ease-out',
        'slide-up': 'slide-up 0.35s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        tvprod: {
          "primary": "var(--md-sys-color-primary)",
          "primary-content": "var(--md-sys-color-on-primary)",
          "secondary": "var(--md-sys-color-secondary)",
          "secondary-content": "var(--md-sys-color-on-secondary)",
          "accent": "var(--md-sys-color-tertiary)",
          "accent-content": "var(--md-sys-color-on-tertiary)",
          "neutral": "var(--md-sys-color-surface-container-high)",
          "neutral-content": "var(--md-sys-color-on-surface)",
          "base-100": "var(--md-sys-color-surface-bright)",
          "base-200": "var(--md-sys-color-surface-container-low)",
          "base-300": "var(--md-sys-color-surface-container)",
          "base-content": "var(--md-sys-color-on-surface)",
          "info": "var(--md-sys-color-info)",
          "info-content": "var(--md-sys-color-on-info)",
          "success": "var(--md-sys-color-success)",
          "success-content": "var(--md-sys-color-on-success)",
          "warning": "var(--md-sys-color-warning)",
          "warning-content": "var(--md-sys-color-on-warning)",
          "error": "var(--md-sys-color-error)",
          "error-content": "var(--md-sys-color-on-error)",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.375rem",
          "--rounded-badge": "9999px",
          "--animation-btn": "0.15s",
          "--animation-input": "0.15s",
          "--btn-focus-scale": "0.97",
          "--tab-radius": "0.5rem",
        },
      },
      {
        tvprodDark: {
          "base-100": "var(--md-sys-color-surface)",
          "base-200": "var(--md-sys-color-surface-container-low)",
          "base-300": "var(--md-sys-color-surface-container)",
          "base-content": "var(--md-sys-color-on-surface)",
          "primary": "var(--md-sys-color-primary)",
          "primary-content": "var(--md-sys-color-on-primary)",
          "secondary": "var(--md-sys-color-secondary)",
          "secondary-content": "var(--md-sys-color-on-secondary)",
          "accent": "var(--md-sys-color-tertiary)",
          "accent-content": "var(--md-sys-color-on-tertiary)",
          "neutral": "var(--md-sys-color-surface-container-high)",
          "neutral-content": "var(--md-sys-color-on-surface)",
          "info": "var(--md-sys-color-info)",
          "info-content": "var(--md-sys-color-on-info)",
          "success": "var(--md-sys-color-success)",
          "success-content": "var(--md-sys-color-on-success)",
          "warning": "var(--md-sys-color-warning)",
          "warning-content": "var(--md-sys-color-on-warning)",
          "error": "var(--md-sys-color-error)",
          "error-content": "var(--md-sys-color-on-error)",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.375rem",
          "--rounded-badge": "9999px",
          "--animation-btn": "0.15s",
          "--animation-input": "0.15s",
          "--btn-focus-scale": "0.97",
          "--tab-radius": "0.5rem",
        },
      },
    ],
    darkTheme: "tvprodDark",
    themeRoot: ":root",
    logs: false,
  },
};
