/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './Views/**/*.cshtml',
    './wwwroot/js/**/*.js',
    './node_modules/preline/dist/*.js',
  ],
  theme: {
    extend: {
      colors: {
        /* Semantic tokens */
        bg: 'var(--color-bg)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'bg-hover': 'var(--color-bg-hover)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        text: 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-disabled': 'var(--color-text-disabled)',

        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-foreground': 'var(--color-primary-foreground)',
        'primary-subtle': 'var(--color-primary-subtle)',
        'primary-border': 'var(--color-primary-border)',

        secondary: 'var(--color-secondary)',
        'secondary-hover': 'var(--color-secondary-hover)',
        'secondary-foreground': 'var(--color-secondary-foreground)',
        'secondary-subtle': 'var(--color-secondary-subtle)',

        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-foreground': 'var(--color-accent-foreground)',
        'accent-subtle': 'var(--color-accent-subtle)',

        success: 'var(--color-success)',
        'success-hover': 'var(--color-success-hover)',
        'success-foreground': 'var(--color-success-foreground)',
        'success-subtle': 'var(--color-success-subtle)',

        warning: 'var(--color-warning)',
        'warning-hover': 'var(--color-warning-hover)',
        'warning-foreground': 'var(--color-warning-foreground)',
        'warning-subtle': 'var(--color-warning-subtle)',

        danger: 'var(--color-danger)',
        'danger-hover': 'var(--color-danger-hover)',
        'danger-foreground': 'var(--color-danger-foreground)',
        'danger-subtle': 'var(--color-danger-subtle)',

        info: 'var(--color-info)',
        'info-hover': 'var(--color-info-hover)',
        'info-foreground': 'var(--color-info-foreground)',
        'info-subtle': 'var(--color-info-subtle)',

        muted: 'var(--color-text-secondary)',
        'muted-foreground': 'var(--color-text-secondary)',

        ring: 'var(--color-ring)',
        foreground: 'var(--color-text)',

        /* Deprecated — kept for backward compatibility during migration */
        'sys-primary': 'var(--color-primary)',
        'sys-on-primary': 'var(--color-primary-foreground)',
        'sys-primary-container': 'var(--color-primary-subtle)',
        'sys-on-primary-container': 'var(--color-primary)',
        'sys-secondary': 'var(--color-secondary)',
        'sys-on-secondary': 'var(--color-secondary-foreground)',
        'sys-secondary-container': 'var(--color-secondary-subtle)',
        'sys-on-secondary-container': 'var(--color-secondary)',
        'sys-tertiary': 'var(--color-accent)',
        'sys-on-tertiary': 'var(--color-accent-foreground)',
        'sys-tertiary-container': 'var(--color-accent-subtle)',
        'sys-on-tertiary-container': 'var(--color-accent)',
        'sys-error': 'var(--color-danger)',
        'sys-on-error': 'var(--color-danger-foreground)',
        'sys-error-container': 'var(--color-danger-subtle)',
        'sys-on-error-container': 'var(--color-danger)',
        'sys-success': 'var(--color-success)',
        'sys-on-success': 'var(--color-success-foreground)',
        'sys-success-container': 'var(--color-success-subtle)',
        'sys-on-success-container': 'var(--color-success)',
        'sys-warning': 'var(--color-warning)',
        'sys-on-warning': 'var(--color-warning-foreground)',
        'sys-warning-container': 'var(--color-warning-subtle)',
        'sys-on-warning-container': 'var(--color-warning)',
        'sys-info': 'var(--color-info)',
        'sys-on-info': 'var(--color-info-foreground)',
        'sys-info-container': 'var(--color-info-subtle)',
        'sys-on-info-container': 'var(--color-info)',
        'sys-surface': 'var(--color-surface)',
        'sys-surface-dim': 'var(--color-bg)',
        'sys-surface-bright': 'var(--color-surface)',
        'sys-on-surface': 'var(--color-text)',
        'sys-on-surface-variant': 'var(--color-text-secondary)',
        'sys-outline': 'var(--color-border)',
        'sys-outline-variant': 'var(--color-border-light)',
      },
      fontFamily: {
        sans: ['Cairo', 'Almarai', 'Segoe UI', 'sans-serif'],
      },
      borderRadius: {
        xl: '14px',
        '2xl': '18px',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        float: 'var(--shadow-float)',
        topbar: 'var(--shadow-topbar)',
      },
      keyframes: {
        'eq-bar': { '0%, 100%': { transform: 'scaleY(0.35)' }, '50%': { transform: 'scaleY(1)' } },
        'onair-pulse': { '0%, 100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.45', transform: 'scale(0.82)' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
      },
      animation: {
        'eq-bar': 'eq-bar 1s ease-in-out infinite',
        'onair-pulse': 'onair-pulse 1.6s ease-in-out infinite',
        'fade-in': 'fade-in 0.25s ease-out',
        'slide-up': 'slide-up 0.35s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
      },
    },
  },
  plugins: [],
};
