// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq.Expressions;

namespace Domain.Models;

public partial class BroadcastWorkflowDBContext : IdentityDbContext<ApplicationUser, ApplicationRole, int>
{

    // ✅ هذا هو الكونستراكتور المطلوب حصراً ليعمل مع IDBContextFactory
    public BroadcastWorkflowDBContext(DbContextOptions<BroadcastWorkflowDBContext> options)
        : base(options) // <--- السحر كله في تمرير الـ options للكلاس الأساسي
    {
    }

    // DbSets خاصة بـ Identity (تُضاف تلقائياً عبر base.OnModelCreating)
    // - AspNetUsers (ApplicationUser)
    // - AspNetRoles (ApplicationRole)
    // - AspNetUserRoles, AspNetUserClaims, AspNetUserTokens, AspNetRoleClaims
    // - AspNetUserLogins

    // استخدام التعبير البدني (Expression-bodied) لتعريف الـ DbSets (أمان أكثر)
    public virtual DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public virtual DbSet<Correspondent> Correspondents => Set<Correspondent>();
    public virtual DbSet<CorrespondentCoverage> CorrespondentCoverages => Set<CorrespondentCoverage>();
    public virtual DbSet<Episode> Episodes => Set<Episode>();
    public virtual DbSet<EpisodeStatus> EpisodeStatuses => Set<EpisodeStatus>();
    public virtual DbSet<EpisodeGuest> EpisodeGuests => Set<EpisodeGuest>();
    public virtual DbSet<ExecutionLog> ExecutionLogs => Set<ExecutionLog>();
    public virtual DbSet<Guest> Guests => Set<Guest>();
    public virtual DbSet<Program> Programs => Set<Program>();
    public virtual DbSet<Employee> Employees => Set<Employee>();
    public virtual DbSet<StaffRole> StaffRoles => Set<StaffRole>();
    public virtual DbSet<EpisodeEmployee> EpisodeEmployees => Set<EpisodeEmployee>();
    public virtual DbSet<EpisodeCorrespondent> EpisodeCorrespondents => Set<EpisodeCorrespondent>();
    public virtual DbSet<SocialMediaPlatform> SocialMediaPlatforms => Set<SocialMediaPlatform>();
    public virtual DbSet<SocialMediaPublishingLog> SocialMediaPublishingLogs => Set<SocialMediaPublishingLog>();
    public virtual DbSet<SocialMediaPublishingLogPlatform> SocialMediaPublishingLogPlatforms => Set<SocialMediaPublishingLogPlatform>();
    public virtual DbSet<WebsitePublishingLog> WebsitePublishingLogs => Set<WebsitePublishingLog>();
    public new virtual DbSet<Role> Roles => Set<Role>();
    public new virtual DbSet<User> Users => Set<User>();
    public virtual DbSet<Permission> Permissions => Set<Permission>();
    public virtual DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public virtual DbSet<DatabaseBackupLog> DatabaseBackupLogs => Set<DatabaseBackupLog>();


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // ✨ هام: استدعاء base.OnModelCreating لإنشاء جداول Identity (AspNetUsers, AspNetRoles, ...)
        base.OnModelCreating(modelBuilder);

        // ✨ السحر هنا: تطبيق كل الإعدادات من مجلد Configurations تلقائياً
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(BroadcastWorkflowDBContext).Assembly);

        // تخصيص أسماء جداول Identity (اختياري: نُبقي الأسماء الافتراضية AspNetUsers, AspNetRoles)
        // modelBuilder.Entity<ApplicationUser>().ToTable("AspNetUsers");
        // modelBuilder.Entity<ApplicationRole>().ToTable("AspNetRoles");

        // تطبيق الـ Seed Data للـ EpisodeStatus
        modelBuilder.Entity<EpisodeStatus>().HasData(
            new EpisodeStatus { StatusId = 0, StatusName = "Planned", DisplayName = "مجدولة", SortOrder = 0 },
            new EpisodeStatus { StatusId = 1, StatusName = "Executed", DisplayName = "منفّذة", SortOrder = 1 },
            new EpisodeStatus { StatusId = 2, StatusName = "Published", DisplayName = "منشورة", SortOrder = 2 },
            new EpisodeStatus { StatusId = 3, StatusName = "WebsitePublished", DisplayName = "منشورة على الموقع", SortOrder = 3 },
            new EpisodeStatus { StatusId = 4, StatusName = "Cancelled", DisplayName = "ملغاة", SortOrder = 4 }
        );

        // إضافة فهارس لتحسين الأداء
        modelBuilder.Entity<Episode>().HasIndex(e => e.StatusId);
        modelBuilder.Entity<Episode>().HasIndex(e => e.ScheduledExecutionTime);
        modelBuilder.Entity<EpisodeGuest>().HasIndex(eg => eg.EpisodeId);
        modelBuilder.Entity<SocialMediaPublishingLog>().HasIndex(l => l.EpisodeGuestId);
        modelBuilder.Entity<SocialMediaPublishingLog>().HasIndex(l => l.PublishedAt);
        modelBuilder.Entity<WebsitePublishingLog>().HasIndex(l => l.EpisodeId);
        modelBuilder.Entity<WebsitePublishingLog>().HasIndex(l => l.PublishedAt);
        modelBuilder.Entity<ExecutionLog>().HasIndex(l => l.EpisodeId);
        modelBuilder.Entity<ExecutionLog>().HasIndex(l => l.CreatedAt);
        modelBuilder.Entity<Employee>().HasIndex(e => e.FullName).HasDatabaseName("IX_Employees_Active_FullName").HasFilter("[IsActive] = 1");


        // ✨ إصلاح خلل الحذف المنطقي: تطبيق الفلتر على أي كيان يرث من BaseEntity
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            if (typeof(BaseEntity).IsAssignableFrom(entityType.ClrType))
            {
                modelBuilder.Entity(entityType.ClrType).HasQueryFilter(
                    GenerateSoftDeleteFilter(entityType.ClrType)
                );
            }
        }


        ConfigureAuditRelationships<Role>(modelBuilder);
        ConfigureAuditRelationships<Employee>(modelBuilder);
        ConfigureAuditRelationships<StaffRole>(modelBuilder);
        ConfigureAuditRelationships<EpisodeEmployee>(modelBuilder);
        ConfigureAuditRelationships<EpisodeCorrespondent>(modelBuilder);
        ConfigureAuditRelationships<SocialMediaPlatform>(modelBuilder);
        ConfigureAuditRelationships<SocialMediaPublishingLog>(modelBuilder);
        ConfigureAuditRelationships<SocialMediaPublishingLogPlatform>(modelBuilder);
        ConfigureAuditRelationships<WebsitePublishingLog>(modelBuilder);
        ConfigureAuditRelationships<ExecutionLog>(modelBuilder);
        ConfigureAuditRelationships<DatabaseBackupLog>(modelBuilder);

        OnModelCreatingPartial(modelBuilder);
    }

    // دالة مساعدة لبناء فلتر الحذف المنطقي ديناميكياً لكل كيان
    private static LambdaExpression GenerateSoftDeleteFilter(Type entityType)
    {
        var parameter = System.Linq.Expressions.Expression.Parameter(entityType, "e");
        var property = System.Linq.Expressions.Expression.Property(parameter, nameof(BaseEntity.IsActive));
        var condition = System.Linq.Expressions.Expression.Equal(property, System.Linq.Expressions.Expression.Constant(true));
        return System.Linq.Expressions.Expression.Lambda(condition, parameter);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    private void ConfigureAuditRelationships<T>(ModelBuilder modelBuilder) where T : BaseEntity
    {
        modelBuilder.Entity<T>()
            .HasOne(e => e.CreatedByUser)
            .WithMany()
            .HasForeignKey(e => e.CreatedByUserId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<T>()
            .HasOne(e => e.UpdatedByUser)
            .WithMany()
            .HasForeignKey(e => e.UpdatedByUserId)
            .OnDelete(DeleteBehavior.Restrict);

        // ✨ تم إزالة HasQueryFilter من هنا — الفلتر يُطبّق مركزياً عبر حلقة GenerateSoftDeleteFilter أعلاه
        // تطبيق الفلتر هنا كان يسبب تكراراً: الفلتر يُطبّق مرتين (مرة من الحلقة ومرة من هنا)
        // المصدر الوحيد للحقيقة الآن هو حلقة GenerateSoftDeleteFilter في سطر 71-79
    }


}
