// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class Correspondent : BaseEntity
{
    public int CorrespondentId { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string AssignedLocations { get; set; }

    public virtual ICollection<CorrespondentCoverage> CorrespondentCoverages { get; set; } = new List<CorrespondentCoverage>();
}