// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class CorrespondentCoverage : BaseEntity
{
    public int CoverageId { get; set; }

    public int CorrespondentId { get; set; }

    public int? GuestId { get; set; }

    public string Location { get; set; }

    public string Topic { get; set; }

    public DateTime? ScheduledTime { get; set; }

    public DateTime? ActualTime { get; set; }

    public virtual Correspondent Correspondent { get; set; }

    public virtual Guest Guest { get; set; }
}