// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

public partial class Episode : BaseEntity
{
    public int EpisodeId { get; set; }

    public int ProgramId { get; set; }

    public string EpisodeName { get; set; }

    public string EpisodeDescription { get; set; }

    public DateTime? ScheduledExecutionTime { get; set; }

    public DateTime? ActualExecutionTime { get; set; }

    //public byte Status { get; set; }

    public string SpecialNotes { get; set; }

    /// <summary>
    /// سبب إلغاء الحلقة — يُملأ فقط عند الإلغاء (StatusId = 4).
    /// مخزن مباشرة في الجدول لتفادي الاستعلام على AuditLogs.
    /// </summary>
    public string? CancellationReason { get; set; }

    // ✅ تم إزالة IsWebsitePublished لمنع تكرار البيانات وتضاربها مع جدول WebsitePublishingLogs وحالة الحلقة

    // ✅ أضف هذين السطرين مكانه:
    public byte StatusId { get; set; }

    [ForeignKey("StatusId")]
    public virtual EpisodeStatus EpisodeStatus { get; set; } = null!;

    public virtual ICollection<EpisodeGuest> EpisodeGuests { get; set; } = new List<EpisodeGuest>();

    public virtual ICollection<ExecutionLog> ExecutionLogs { get; set; } = new List<ExecutionLog>();

    public virtual Program Program { get; set; }


    public virtual ICollection<WebsitePublishingLog> WebsitePublishingLogs { get; set; } = new List<WebsitePublishingLog>();
    public virtual ICollection<EpisodeEmployee> EpisodeEmployees { get; set; } = new List<EpisodeEmployee>();
    public virtual ICollection<EpisodeCorrespondent> EpisodeCorrespondents { get; set; } = new List<EpisodeCorrespondent>();
}