// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class EpisodeGuest : BaseEntity
{
    public int EpisodeGuestId { get; set; }

    public int EpisodeId { get; set; }

    public int GuestId { get; set; }

    public string? Topic { get; set; }
    public TimeSpan? HostingTime { get; set; }   // ✅ ساعة الاستضافة (مثلاً: 08:30)

    public GuestClipStatus ClipStatus { get; set; } = GuestClipStatus.Pending;
    public string? ClipNotes { get; set; }

    public virtual Episode Episode { get; set; } = null!;

    public virtual Guest Guest { get; set; } = null!;

    public virtual ICollection<SocialMediaPublishingLog> SocialMediaPublishingLogs { get; set; } = new List<SocialMediaPublishingLog>();
}