// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class ExecutionLog : BaseEntity
{
    public int ExecutionLogId { get; set; }

    public int EpisodeId { get; set; }

    public int ExecutedByUserId { get; set; }

    public int? DurationMinutes { get; set; }

    public string ExecutionNotes { get; set; }

    public string IssuesEncountered { get; set; }

    public virtual Episode Episode { get; set; }

    public virtual User ExecutedByUser { get; set; }
}