// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class Guest : BaseEntity
{
    public int GuestId { get; set; }

    public string FullName { get; set; }

    public string Organization { get; set; }

    public string PhoneNumber { get; set; }

    public string EmailAddress { get; set; }

    public virtual ICollection<CorrespondentCoverage> CorrespondentCoverages { get; set; } = new List<CorrespondentCoverage>();
    public virtual ICollection<EpisodeGuest> EpisodeGuests { get; set; } = new List<EpisodeGuest>();
}