// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models
{
    public partial interface IBroadcastWorkflowDBContextProcedures
    {
        Task<int> sp_SoftDeleteGuestAsync(int? guestId, int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_UpdateEpisodeStatusAsync(int? episodeId, byte? newStatus, int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
