// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class Program : BaseEntity
{
    public int ProgramId { get; set; }

    public string ProgramName { get; set; }

    public string ProgramDescription { get; set; }

    public string Category { get; set; }

    public virtual ICollection<Episode> Episodes { get; set; } = new List<Episode>();
}