// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class User : BaseEntity
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string EmailAddress { get; set; }

    public string PhoneNumber { get; set; }

    public int RoleId { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public virtual ICollection<ExecutionLog> ExecutionLogs { get; set; } = new List<ExecutionLog>();



    public virtual ICollection<User> InverseCreatedByUser { get; set; } = new List<User>();

    public virtual ICollection<User> InverseUpdatedByUser { get; set; } = new List<User>();



    public virtual ICollection<SocialMediaPublishingLog> SocialMediaPublishingLogs { get; set; } = new List<SocialMediaPublishingLog>();

    public virtual ICollection<WebsitePublishingLog> WebsitePublishingLogs { get; set; } = new List<WebsitePublishingLog>();

    public virtual Role Role { get; set; }
}